version: '3.8'
services:
  nginx:
    image: rlatndls113/myweb:1.0
    deploy:
      replicas: 3
      placement:
        constraints: [ node.role == worker ]
    volumes:
      - nginx_vol:/usr/share/nginx/html
    ports:
      - "8888.80"

volumes:
  nginx_vol:
    driver: local
    driver_opts:
      type: "nfs4"
      o: "addr=211.183.3.200,rw"
      device: ":/nginx"
